version: '3'
services:
  web:
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    build: .
    env_file: .env
    restart: always
    command: bash -I -c "python3 app.py"
    links:
      - postgres
      - redis
    volumes:
      - .:/code
      - ./public/static:/code/public/static
      - ./public/media:/code/public/media
    ports:
      - 8000:8000
  postgres:
    networks:
      - backend
    image: postgres:9.6
    env_file: .env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "8003:5432"
  redis:
    image: redis:latest
    networks:
      - backend
    env_file: .env
    volumes:
      - ./data/redis_data:/data
    ports:
      - "6379:6379"

networks:
  backend: