connection:
  database: aiohttp_sqlalchemy_alembic
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
  type: postgresql
redis:
  host: 127.0.0.1
  port: 6379

host: 127.0.0.1
port: 8080
root_path: